/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bed-ward/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetBedWardPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bed-ward/patients/{patientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetBedWardPatient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bed-ward/patients/admit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdmitPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emergency-wards/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEmergencyPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emergency-wards/patients/{patientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEmergencyPatient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emergency-wards/patients/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RegisterEmergencyPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emergency-wards/patients/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TransferEmergencyPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BedWardPatient: {
            /** Format: uuid */
            id?: string;
            personalIdentifier?: string | null;
            familyName?: string | null;
            givenNames?: string | null;
        };
        BedWardPatientListItem: {
            /** Format: uuid */
            id?: string;
            personalIdentifier?: string | null;
            familyName?: string | null;
            givenNames?: string | null;
        };
        EmergencyPatient: {
            /** Format: uuid */
            patientId?: string;
            familyName?: string | null;
            givenNames?: string | null;
        };
        EmergencyPatientListItem: {
            /** Format: uuid */
            patientId?: string;
            familyName?: string | null;
            givenNames?: string | null;
            status?: components["schemas"]["EmergencyPatientStatus"];
        };
        /** @enum {string} */
        EmergencyPatientStatus: "Registered" | "InTransfer" | "Discharged";
        EmergencyRegistration: {
            personalIdentifier?: string | null;
            familyName?: string | null;
            givenNames?: string | null;
            reason?: string | null;
        };
        PatientAdmission: {
            /** Format: uuid */
            patientId?: string;
        };
        TransferRequest: {
            /** Format: uuid */
            patientId?: string;
            familyName?: string | null;
            givenNames?: string | null;
            wardIdentifier?: string | null;
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetBedWardPatients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BedWardPatientListItem"][];
                };
            };
        };
    };
    GetBedWardPatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BedWardPatient"];
                };
            };
        };
    };
    AdmitPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatientAdmission"];
                "text/json": components["schemas"]["PatientAdmission"];
                "application/*+json": components["schemas"]["PatientAdmission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetEmergencyPatients: {
        parameters: {
            query?: {
                status?: components["schemas"]["EmergencyPatientStatus"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyPatientListItem"][];
                };
            };
        };
    };
    GetEmergencyPatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyPatient"];
                };
            };
        };
    };
    RegisterEmergencyPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmergencyRegistration"];
                "text/json": components["schemas"]["EmergencyRegistration"];
                "application/*+json": components["schemas"]["EmergencyRegistration"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransferEmergencyPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
                "text/json": components["schemas"]["TransferRequest"];
                "application/*+json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
